### ISSUE TITLE
Warning in pixReadMemPng: work-around: writing to a temp file

### ISSUE THREAD

**Issue by unagitated** [mdelete/node-tesseract-native#5]
I always get the following warning. Seems to have something to do with the use of Leptonica. Any ideas?
Thanks
/Peter

 node-tesseract-native git:(master) ✗ sudo node test.js "1.png"
Tesseract Open Source OCR Engine v3.02.02 with Leptonica
<Buffer 89 50 4e 47 0d 0a 1a 0a 00 00 00 0d 49 48 44 52 00 00 13 5e 00 00 1b 69 08 02 00 00 00 6e 02 69 d2 00 00 20 00 49 44 41 54 78 9c ec db 41 0d 00 20 10 c0 ...>
Warning in pixReadMemPng: work-around: writing to a temp file

test.js:12
      throw err;
            ^
3

**Comment by UnknownCUnknown** [comment]
I have met the same problem.Have you found some ways to solve it?

**Comment by shreyansb** [comment]
+1 any update?

**Comment by mdelete** [comment]
As stated in the README this module just works with linux for now. The warning comes from Leptonica which complains about a missing fmemopen(), a call only available on linux systems, and then tries to work-around by using a temp file. I haven't figured out yet why the temp-file breaks everything. I'll have to rewrite the module anyways, because the node C++ API changed and this is incompatible with node 0.12.x and iojs.

**Comment by mdelete** [comment]
Tested it with OSX (Nodejs 0.12.x), the warning is shown, but no exception is thrown.
